version: '3.8'
services:


  mongo:
    image: 'mongo:4.2.6-bionic'
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - ./mongodata:/data/db
    restart: always


  mongo_express:
    image: mongo-express
    container_name: mongo_express
    depends_on:
      - 'mongo'
    ports:
      - '8081:8091'
    restart: always