// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserDetailsClient is the client API for UserDetails service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserDetailsClient interface {
	GetUsername(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Username, error)
}

type userDetailsClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDetailsClient(cc grpc.ClientConnInterface) UserDetailsClient {
	return &userDetailsClient{cc}
}

func (c *userDetailsClient) GetUsername(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Username, error) {
	out := new(Username)
	err := c.cc.Invoke(ctx, "/UserDetails/GetUsername", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDetailsServer is the server API for UserDetails service.
// All implementations must embed UnimplementedUserDetailsServer
// for forward compatibility
type UserDetailsServer interface {
	GetUsername(context.Context, *UserId) (*Username, error)
	mustEmbedUnimplementedUserDetailsServer()
}

// UnimplementedUserDetailsServer must be embedded to have forward compatible implementations.
type UnimplementedUserDetailsServer struct {
}

func (UnimplementedUserDetailsServer) GetUsername(context.Context, *UserId) (*Username, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsername not implemented")
}
func (UnimplementedUserDetailsServer) mustEmbedUnimplementedUserDetailsServer() {}

// UnsafeUserDetailsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserDetailsServer will
// result in compilation errors.
type UnsafeUserDetailsServer interface {
	mustEmbedUnimplementedUserDetailsServer()
}

func RegisterUserDetailsServer(s grpc.ServiceRegistrar, srv UserDetailsServer) {
	s.RegisterService(&UserDetails_ServiceDesc, srv)
}

func _UserDetails_GetUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDetailsServer).GetUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserDetails/GetUsername",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDetailsServer).GetUsername(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

// UserDetails_ServiceDesc is the grpc.ServiceDesc for UserDetails service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserDetails_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserDetails",
	HandlerType: (*UserDetailsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsername",
			Handler:    _UserDetails_GetUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
